content: |-
  {{ .Header }}

  # Basic Example

  Grant access to the AWS EKS cluster by creating a new `aws-auth` configmap with the `map_roles`, `map_user` and `map_accounts`.

  ℹ️ An AWS EKS cluster without managed node groups or fargate profiles will not automatically create the `aws-auth` configmap.

  ```hcl
  {{ include "main.tf" }}
  ```

  ## Running this module manually

  1. Install [Terraform](https://www.terraform.io/) and make sure it's on your `PATH`.
  1. Run `terraform init`.
  1. Run `terraform apply`.
  1. When you're done, run `terraform destroy`.

  ## Running automated tests against this module

  1. Install [Terraform](https://www.terraform.io/) and make sure it's on your `PATH`.
  1. Install [Golang](https://golang.org/) and make sure this code is checked out into your `GOPATH`.
  1. `cd test`
  1. `go test terraform_basic_test.go -v`

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Modules }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}
